[package]
name = "rdpm_rdp_host"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
windows.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
tokio.workspace = true

[build-dependencies]
cc = { version = "1.2", features = ["parallel"] }
